apiVersion: v1
kind: Service
metadata:
  name: flask-app-deployment
  labels:
    run: flask-app-deployment
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask-app-deployment